name: Lint Code

on:
  push:
    branches: [ ci-lint, main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Fix permissions
        run: chmod -R +x node_modules/.bin

      - name: Lint HTML
        run: npx htmlhint "public/**/*.html"

      - name: Lint CSS
        run: npx stylelint "public/css/**/*.css"

      - name: Lint JavaScript
        run: npx eslint "public/js/**/*.js"